microservice:
  group-management-service:
    endpoints:
      endpoint:
        uri: http://GROUP-MANAGEMENT-SERVICE/manage/getGroup/group
  email-management-service:
    endpoints:
      endpoint:
        uri: http://EMAIL-MANAGEMENT-SERVICE/mail/send
